### ISSUE TITLE
Redirection should not happen for post requests

### ISSUE THREAD

**Issue by phumberdroz** [ladjs/i18n#10]
I have an application that is maintained by a different company that does a post request to a tool of ours.

If we redirect them we lose the post body

**Comment by phumberdroz** [comment]
I just saw that I might be able to use: `feat: added redirect ignore glob support`

**Comment by niftylettuce** [comment]
We have resolved this as of v3.0.0 released to npm :tada:

There are two new options added `redirectIgnoresNonGetMethods` (Boolean, defaults to `true`) and `stringify` (Object for [qs.stringify](https://github.com/ljharb/qs), and has sensible industry standard defaults of `{ addQueryPrefix: true, format: 'RFC1738', arrayFormat: 'indices' }`).  As of v3.0.0 all non-GET requests will *NOT* be redirected to locale specific path.  If you wish to turn this behavior off, pass `new I18n({ redirectIgnoresNonGetMethods: false })`.

```sh
npm install @ladjs/i18n@latest
```

or with yarn:

```sh
yarn add @ladjs/i18n@latest
```

Note that we have also version bumped deps in `@ladjs/web` and `@ladjs/api` (as well as across all of @ladjs and @cabinjs projects), and you can install the latest with `@ladjs/web@latest` and `@ladjs/api@latest`.

Let me know if you find any further issues, thanks so much!
