### ISSUE TITLE
Provide custom locale detection option

### ISSUE THREAD

**Issue by nemphys** [ladjs/i18n#26]
It would be nice to have the ability to provide a custom function config option for locale detection (which would be executed first, before the hard-coded url/cookie/Accept-Language/lastLocale checks).
I am trying to store the locale in the session (not a separate cookie) and there is currently no way to do that.

EDIT: I can provide a PR if you are interested

**Comment by niftylettuce** [comment]
Yes, PR welcome!

**Comment by niftylettuce** [comment]
Curious @nemphys are you using @ladjs too?

**Comment by niftylettuce** [comment]
v7.1.0 released https://github.com/ladjs/i18n/releases/tag/v7.1.0 @nemphys
