### ISSUE TITLE
Vulnerability in nested underscore dependency

### ISSUE THREAD

**Issue by nemphys** [ladjs/i18n#28]
Today I just started seeing this:

# npm audit report

underscore  1.3.2 - 1.12.0
Severity: high
Arbitrary Code Execution - https://npmjs.com/advisories/1674
No fix available
node_modules/underscore
  country-language  *
  Depends on vulnerable versions of underscore
  node_modules/country-language
    @ladjs/i18n  *
    Depends on vulnerable versions of country-language
    Depends on vulnerable versions of i18n-locales
    node_modules/@ladjs/i18n
    i18n-locales  >=0.0.3
    Depends on vulnerable versions of country-language
    node_modules/i18n-locales

A dependency update would be greatly appreciated.

**Comment by niftylettuce** [comment]
Done!  THANK YOU!  download v7.2.0 to use!

https://github.com/ladjs/i18n/releases/tag/v7.2.0

**Comment by nemphys** [comment]
Thank you for the update, but I still get the following:

# npm audit report

underscore  1.3.2 - 1.12.0
Severity: high
Arbitrary Code Execution - https://npmjs.com/advisories/1674
No fix available
node_modules/underscore
  country-language  *
  Depends on vulnerable versions of underscore
  node_modules/country-language
    @ladjs/i18n  *
    Depends on vulnerable versions of country-language
    node_modules/@ladjs/i18n

**Comment by niftylettuce** [comment]
Oh derp, my bad I forgot to fix it in this package (not just in i18n-locales)

Sec!

**Comment by niftylettuce** [comment]
OK https://github.com/ladjs/i18n/releases/tag/v7.2.1 v7.2.1 should be good to go!

**Comment by nemphys** [comment]
Thanx!
