### ISSUE TITLE
Consider to import i18n-node as instance instead of singleton

### ISSUE THREAD

**Issue by alexfranco90** [ladjs/i18n#29]
From 0.12.0 [mashpie/i18n-node](https://github.com/mashpie/i18n-node) give you the possibility of using it as instance instead of importing it as singleton.

Maybe you should consider changing your code?
```javascript
/*** FROM ***/
const i18n = require('i18n')
// ...
Object.assign(this, i18n)

/*** TO ***/
const { I18n } = require('i18n')
// ...
Object.assign(this, new I18n())
```
This way, if there is a project that for some reason already import mashpie/i18n-node, ladjs/i18n dont change the configuration at project level.

I don't know if it is intentional in ladjs/i18n to use it as singleton but i personally faced this problem because i was using forwardemail/email-templates without deep checking how his dependency to this package work and everytime i was sending a translated email, i18n-node configuration changed.
In my case it was easily fixed by replacing the project level singleton with an instance but maybe a package like this one should prevent this type of bugs by using itself a personal instance instead of operating on a singleton.

**Comment by niftylettuce** [comment]
I would absolutely do this!  Great idea.  Can you submit a pull request?

**Comment by alexfranco90** [comment]
Sure I'm gonna do it!

**Comment by niftylettuce** [comment]
Done!  THANK YOU!  download v7.2.0 to use!

https://github.com/ladjs/i18n/releases/tag/v7.2.0

**Comment by niftylettuce** [comment]
v7.2.1 released
