### ISSUE TITLE
Invalid or Unexpected Token

### ISSUE THREAD

**Issue by dagreatbrendino** [ladjs/i18n#31]
Newest push seems to be causing some issues when compiled in react. I'm using the package email-templates and when npm tries to install/build I'm getting the following error shown in this gyazo screenshot. https://gyazo.com/bfe0fdc3e3a3b32b5319dff54680aebe 
Seems to have to do with changing 31556952000 to 31_556_952_000. Let me know if I'm just being stupid and the issue is something else entirely :)

**Comment by Log3n** [comment]
@dagreatbrendino in our case it was fixed by upgrading from nodejs v10 to v12.  v10 does not support the es2021 feature numeric separator.

**Comment by niftylettuce** [comment]
I’ll fix this

**Comment by AlainEdwards** [comment]
I am having the same issue. I was starting wonder what I was missing. @niftylettuce would it be faster if we submit a MR?

**Comment by niftylettuce** [comment]
v7.2.3 released to npm https://github.com/ladjs/i18n/releases/tag/v7.2.3
