### ISSUE TITLE
Update to i18n@0.14.1

### ISSUE THREAD

**Issue by enijar** [ladjs/i18n#33]
`i18n@0.13.4` uses the deprecated [messageformat](https://www.npmjs.com/package/messageformat) package. Version `i18n@0.14.1` uses the up-to-date [@messageformat/core](https://www.npmjs.com/package/@messageformat/core) package.

**Comment by niftylettuce** [comment]
Thanks, per https://github.com/mashpie/i18n-node/pull/472 I guess I didn't get notified.

**Comment by niftylettuce** [comment]
v7.2.6 released to npm

https://github.com/ladjs/i18n/releases/tag/v7.2.6
